#! /usr/bin/env python2.7
# vim: filetype=python

from nete.qtgui.main_window import MainWindow
from PyQt5.QtGui import QGuiApplication
import sys


if __name__ == '__main__':
    app = QGuiApplication(sys.argv)

    main_window = MainWindow()
    main_window.show()

    sys.exit(app.exec_())
