#! /usr/bin/env python2.7
# vim: filetype=python

from nete.qtgui.application import Application
import sys


if __name__ == '__main__':
    #import profile
    #profile.run('sys.exit(app.exec_())')

    app = Application(sys.argv)
    app.setOrganizationName('nete')
    app.setApplicationName('nete-qt')

    sys.exit(app.exec_())
